services:
  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 30s
      retries: 50

  fast-api:
    depends_on:
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    user: python
    command: poetry run uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    env_file:
      - .env
    healthcheck:
      test: curl -f http://fast-api:8000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  celery:
    depends_on:
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    user: python
    command: poetry run celery -A src.tasks.celery_app worker --loglevel=info --concurrency=2
    volumes:
      - ./src:/app/src
    env_file:
      - .env

  flower:
    image: mher/flower
    depends_on:
      redis:
        condition: service_healthy
    command: celery flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - FLOWER_PORT=5555
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0