[tool.poetry]
name = "llm-scorecaster"
version = "0.0.1"
description = "This repo calculates and outputs metrics for LLM prompts and responses"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.6"
bert-score = "^0.3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
